name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DENABLE_TSAN=OFF

      - name: Build Test Executables
        working-directory: ${{github.workspace}}/build
        run: |
          make btree_insert_test \
            btree_delete_test \
            btree_concurrent_test

      - name: Run Tests with CTest
        working-directory: ${{github.workspace}}/build
        run: ctest --verbose
