name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

      - name: Build Test Executables
        # We explicitly build each test target by name to ensure they exist before testing.
        working-directory: ${{github.workspace}}/build
        run: make btree_insert_test

      - name: Run Tests with CTest
        # Now that the executables are guaranteed to be built, ctest will find and run them.
        working-directory: ${{github.workspace}}/build
        run: ctest --verbose